name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with your default branch if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. Install dependencies using Yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # 4. Build site with environment variables
      - name: Build site
        run: yarn build

      # 5. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }} 
          publish_dir: ./out
